export enum Constants {
    KINGSIDE_ROOK_COLUMN = 7,
    KINGSIDE_ROOK_DESTINATION_COLUMN = 5,
    KINGSIDE_CASTLING = 2,
    QUEENSIDE_ROOK_COLUMN = 0,
    QUEENSIDE_ROOK_DESTINATION_COLUMN = 3,
    QUEENSIDE_CASTLING = -2
}
